CREATE TABLE [dbo].[EmployeeInvestmentDetails] (
    [id]                                INT             IDENTITY (1, 1) NOT NULL,
    [employee_id]                       INT             NOT NULL,
    [emp_code]                          NCHAR (10)      NOT NULL,
    [financial_year]                    NCHAR (10)      NULL,
    [house_rent_allowance]              DECIMAL (18, 2) NULL,
    [life_insurance_premium]            DECIMAL (18, 2) NULL,
    [provident_fund]                    DECIMAL (18, 2) NULL,
    [public_provident_fund]             DECIMAL (18, 2) NULL,
    [voluntary_provident_fund]          DECIMAL (18, 2) NULL,
    [nsc]                               DECIMAL (18, 2) NULL,
    [interest_nsc]                      DECIMAL (18, 2) NULL,
    [ulip]                              DECIMAL (18, 2) NULL,
    [elss_mutual_fund]                  DECIMAL (18, 2) NULL,
    [tution_fees]                       DECIMAL (18, 2) NULL,
    [principal_repayment_house_loan]    DECIMAL (18, 2) NULL,
    [house_stamp_duty_reg_charges]      DECIMAL (18, 2) NULL,
    [infrastructure_bonds]              DECIMAL (18, 2) NULL,
    [bank_fixed_deposit]                DECIMAL (18, 2) NULL,
    [post_office_term_deposit]          DECIMAL (18, 2) NULL,
    [medical_insurance_premium]         DECIMAL (18, 2) NULL,
    [medical_insurance_premuim_parents] DECIMAL (18, 2) NULL,
    [preventive_health_checkup]         DECIMAL (18, 2) NULL,
    [home_loan_interest]                DECIMAL (18, 2) NULL,
    [created_by]                        NVARCHAR (50)   NULL,
    [created_date]                      DATETIME        NULL,
    [modified_by]                       NVARCHAR (50)   NULL,
    [modified_date]                     DATETIME        NULL,
    CONSTRAINT [PK_EmployeeInvestmentDetails] PRIMARY KEY CLUSTERED ([id] ASC), 
    CONSTRAINT [FK_EmployeeInvestmentDetails_ToTable] FOREIGN KEY ([employee_id]) REFERENCES [Employee]([id])
    
);

