CREATE TABLE [dbo].[Employee] (
    [id]             INT            IDENTITY (1, 1) NOT NULL,
    [emp_code]       NCHAR (10)     NOT NULL,
    [photo_url]      NVARCHAR (MAX) NULL,
    [first_name]     NVARCHAR (50)  NOT NULL,
    [middle_name]    NVARCHAR (50)  NULL,
    [last_name]      NVARCHAR (50)  NULL,
    [gender]         INT            NOT NULL,
    [pan_number]     NCHAR (10)     NULL,
    [marital_status] INT            NOT NULL,
    [personal_email] NVARCHAR (50)  NULL,
    [work_email]     NVARCHAR (50)  NULL,
    [work_phone]     NCHAR (10)     NULL,
    [phone_ext]      NCHAR (5)      NULL,
    [mobile_no]      NCHAR (10)     NULL,
    [date_of_birth]  DATE           NULL,
    [vendor_id]      INT            CONSTRAINT [DF_Employee_vendor_id] DEFAULT ((0)) NOT NULL,
    [active]         BIT            CONSTRAINT [DF_Employee_active] DEFAULT ((0)) NULL,
    [deleted]        BIT            CONSTRAINT [DF_Employee_deleted] DEFAULT ((0)) NULL,
    [created_by]     NVARCHAR (50)  NOT NULL,
    [created_date]   DATETIME       NOT NULL,
    [modified_by]    NVARCHAR (50)  NULL,
    [modified_date]  DATETIME       NULL,
    CONSTRAINT [PK_Employee] PRIMARY KEY CLUSTERED ([id] ASC),
    CONSTRAINT [FK_Employee_Employee] FOREIGN KEY ([id]) REFERENCES [dbo].[Employee] ([id]),
    CONSTRAINT [FK_Employee_Master_Gender] FOREIGN KEY ([gender]) REFERENCES [dbo].[Master] ([id]),
    CONSTRAINT [FK_Employee_Master_Marital_Status] FOREIGN KEY ([marital_status]) REFERENCES [dbo].[Master] ([id])
);

